---
- name: Ping a specific host
  hosts: NonProd
  gather_facts: no
  
   
  tasks:
    - name: Ping the host
      ansible.windows.win_ping:

    - name: Show host info
      debug:
       msg: "Hello from {{ inventory_hostname }}"